version: '3.8'

services:
  battle-arena:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: battle-royale-arena
    ports:
      - "2222:22"      # SSH
      - "8080:8080"    # Health check
      - "9099:9099"    # Service manager (host 9099 -> container 9099)
      - "80:80"        # Web services
    volumes:
      - ./shared:/battle/shared
      - ./logs:/battle/logs
    environment:
      - BATTLE_MODE=ready
    restart: unless-stopped
    networks:
      - battle-network

networks:
  battle-network:
    driver: bridge