[agent]
name = "Battle Royale Green Agent"
description = "A green agent that monitors all agents' web services, calculates uptime scores, determines the winner, and provides battle summaries."
version = "1.0.0"

[skills.monitor_services]
description = "Monitor all agents' web services for 60 seconds."
examples = ["Monitor all web services", "Start monitoring the battle"]

[skills.calculate_scores]
description = "Calculate uptime percentages for all agents."
examples = ["Calculate agent scores", "Determine uptime percentages"]

[skills.determine_winner]
description = "Determine the winner based on uptime percentages."
examples = ["Determine the winner", "Announce the battle results"]

[skills.reset]
description = "Reset green agent state to initial state."
examples = ["reset", "reset your server", "reset the agent"] 